const comparison = [
    {
        _tokenString: 'meth',
        _lineNumber: 1,
        _characterNumber: 1,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: 'func',
        _lineNumber: 1,
        _characterNumber: 6,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '(',
        _lineNumber: 1,
        _characterNumber: 10,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'a',
        _lineNumber: 1,
        _characterNumber: 11,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ':',
        _lineNumber: 1,
        _characterNumber: 12,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'int',
        _lineNumber: 1,
        _characterNumber: 14,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: ',',
        _lineNumber: 1,
        _characterNumber: 17,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'b',
        _lineNumber: 1,
        _characterNumber: 19,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ':',
        _lineNumber: 1,
        _characterNumber: 20,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'int',
        _lineNumber: 1,
        _characterNumber: 21,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: ')',
        _lineNumber: 1,
        _characterNumber: 24,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: ':',
        _lineNumber: 1,
        _characterNumber: 25,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'int',
        _lineNumber: 1,
        _characterNumber: 27,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '{',
        _lineNumber: 2,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'a',
        _lineNumber: 2,
        _characterNumber: 4,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ':',
        _lineNumber: 2,
        _characterNumber: 5,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'int',
        _lineNumber: 2,
        _characterNumber: 7,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '=',
        _lineNumber: 2,
        _characterNumber: 11,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: '9',
        _lineNumber: 2,
        _characterNumber: 13,
        _information: {name: 'INTEGER', fullyQualifiedName: 'TOKENS/LITERALS/INTEGER'},
    },
    {
        _tokenString: ';',
        _lineNumber: 3,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'b',
        _lineNumber: 3,
        _characterNumber: 7,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ':',
        _lineNumber: 3,
        _characterNumber: 8,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'int',
        _lineNumber: 3,
        _characterNumber: 10,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '=',
        _lineNumber: 3,
        _characterNumber: 14,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: '5',
        _lineNumber: 3,
        _characterNumber: 16,
        _information: {name: 'INTEGER', fullyQualifiedName: 'TOKENS/LITERALS/INTEGER'},
    },
    {
        _tokenString: ';',
        _lineNumber: 4,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'c',
        _lineNumber: 4,
        _characterNumber: 7,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ':',
        _lineNumber: 4,
        _characterNumber: 8,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'bool',
        _lineNumber: 4,
        _characterNumber: 10,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ';',
        _lineNumber: 5,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'if',
        _lineNumber: 5,
        _characterNumber: 7,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '(',
        _lineNumber: 5,
        _characterNumber: 9,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'a',
        _lineNumber: 5,
        _characterNumber: 10,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '>',
        _lineNumber: 5,
        _characterNumber: 12,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'b',
        _lineNumber: 5,
        _characterNumber: 14,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ')',
        _lineNumber: 5,
        _characterNumber: 15,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '{',
        _lineNumber: 6,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'c',
        _lineNumber: 6,
        _characterNumber: 11,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '=',
        _lineNumber: 6,
        _characterNumber: 13,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'cap',
        _lineNumber: 6,
        _characterNumber: 15,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: ';',
        _lineNumber: 7,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '}',
        _lineNumber: 8,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'if',
        _lineNumber: 8,
        _characterNumber: 7,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '(',
        _lineNumber: 8,
        _characterNumber: 9,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'a',
        _lineNumber: 8,
        _characterNumber: 10,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '>=',
        _lineNumber: 8,
        _characterNumber: 12,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'b',
        _lineNumber: 8,
        _characterNumber: 15,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ')',
        _lineNumber: 8,
        _characterNumber: 16,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '{',
        _lineNumber: 9,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'c',
        _lineNumber: 9,
        _characterNumber: 11,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '=',
        _lineNumber: 9,
        _characterNumber: 13,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'cap',
        _lineNumber: 9,
        _characterNumber: 15,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: ';',
        _lineNumber: 10,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '}',
        _lineNumber: 11,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'if',
        _lineNumber: 11,
        _characterNumber: 7,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '(',
        _lineNumber: 11,
        _characterNumber: 9,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'a',
        _lineNumber: 11,
        _characterNumber: 10,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '!=',
        _lineNumber: 11,
        _characterNumber: 12,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'b',
        _lineNumber: 11,
        _characterNumber: 15,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ')',
        _lineNumber: 11,
        _characterNumber: 16,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '{',
        _lineNumber: 12,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'c',
        _lineNumber: 12,
        _characterNumber: 11,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '=',
        _lineNumber: 12,
        _characterNumber: 13,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'cap',
        _lineNumber: 12,
        _characterNumber: 15,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: ';',
        _lineNumber: 13,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '}',
        _lineNumber: 14,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'if',
        _lineNumber: 14,
        _characterNumber: 7,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '(',
        _lineNumber: 14,
        _characterNumber: 9,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'a',
        _lineNumber: 14,
        _characterNumber: 10,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '<',
        _lineNumber: 14,
        _characterNumber: 12,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'b',
        _lineNumber: 14,
        _characterNumber: 14,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ')',
        _lineNumber: 14,
        _characterNumber: 15,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '{',
        _lineNumber: 15,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'c',
        _lineNumber: 15,
        _characterNumber: 11,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '=',
        _lineNumber: 15,
        _characterNumber: 13,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'nocap',
        _lineNumber: 15,
        _characterNumber: 15,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: ';',
        _lineNumber: 16,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '}',
        _lineNumber: 17,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'if',
        _lineNumber: 17,
        _characterNumber: 7,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '(',
        _lineNumber: 17,
        _characterNumber: 9,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'a',
        _lineNumber: 17,
        _characterNumber: 10,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '<=',
        _lineNumber: 17,
        _characterNumber: 12,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'b',
        _lineNumber: 17,
        _characterNumber: 15,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ')',
        _lineNumber: 17,
        _characterNumber: 16,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '{',
        _lineNumber: 18,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'c',
        _lineNumber: 18,
        _characterNumber: 11,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '=',
        _lineNumber: 18,
        _characterNumber: 13,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'nocap',
        _lineNumber: 18,
        _characterNumber: 15,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: ';',
        _lineNumber: 19,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '}',
        _lineNumber: 20,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'if',
        _lineNumber: 20,
        _characterNumber: 7,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '(',
        _lineNumber: 20,
        _characterNumber: 9,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'a',
        _lineNumber: 20,
        _characterNumber: 10,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '==',
        _lineNumber: 20,
        _characterNumber: 12,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'b',
        _lineNumber: 20,
        _characterNumber: 15,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: ')',
        _lineNumber: 20,
        _characterNumber: 16,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '{',
        _lineNumber: 21,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'c',
        _lineNumber: 21,
        _characterNumber: 11,
        _information: {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'},
    },
    {
        _tokenString: '=',
        _lineNumber: 21,
        _characterNumber: 13,
        _information: {
            name: 'COMPARISON',
            fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
        },
    },
    {
        _tokenString: 'nocap',
        _lineNumber: 21,
        _characterNumber: 15,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: ';',
        _lineNumber: 22,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '}',
        _lineNumber: 23,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: 'yeet',
        _lineNumber: 23,
        _characterNumber: 7,
        _information: {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'},
    },
    {
        _tokenString: '0',
        _lineNumber: 23,
        _characterNumber: 12,
        _information: {name: 'INTEGER', fullyQualifiedName: 'TOKENS/LITERALS/INTEGER'},
    },
    {
        _tokenString: ';',
        _lineNumber: 24,
        _characterNumber: 1,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
    {
        _tokenString: '}',
        _lineNumber: 24,
        _characterNumber: 3,
        _information: {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'},
    },
];

let comparisonString = '';
for (const token of comparison) {
    comparisonString += `${token._tokenString} ${token._information.name} (${token._lineNumber}, ${token._characterNumber})\n`;
}

export {comparisonString};
