import Token from '../../src/compiler/token';

const tokens = [
    new Token('meth', 1, 1, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('logic', 1, 6, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('(', 1, 11, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token(')', 1, 12, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token(':', 1, 13, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('tuple', 1, 15, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('{', 1, 20, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('boolean', 1, 21, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token(',', 1, 28, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('boolean', 1, 30, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token(',', 1, 37, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('boolean', 1, 39, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('}', 1, 46, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('{', 2, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('a', 2, 4, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(':', 2, 5, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('bool', 2, 7, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('=', 2, 12, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('cap', 2, 14, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token(';', 3, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('b', 3, 7, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(':', 3, 8, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('bool', 3, 10, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('=', 3, 15, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('nocap', 3, 17, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token(';', 4, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('resa', 4, 7, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(':', 4, 11, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('bool', 4, 13, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(';', 5, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('resb', 5, 7, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(':', 5, 11, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('bool', 5, 13, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(';', 6, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('resc', 6, 7, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(':', 6, 11, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('bool', 6, 13, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(';', 7, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('resa', 8, 7, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('=', 8, 12, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('cap', 8, 14, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('if', 8, 18, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('a', 8, 21, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('and', 8, 23, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('b', 8, 27, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('==', 8, 29, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('cap', 8, 32, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('else', 8, 36, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('resa', 8, 41, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('=', 8, 46, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('nocap', 8, 48, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token(';', 9, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('resb', 9, 7, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('=', 9, 12, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('cap', 9, 14, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('if', 9, 18, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('a', 9, 21, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('or', 9, 23, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('b', 9, 26, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('==', 9, 28, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('cap', 9, 31, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('else', 9, 35, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('resb', 9, 40, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('=', 9, 45, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('nocap', 9, 47, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token(';', 10, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('resc', 11, 7, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('=', 11, 12, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('!', 11, 14, {
        name: 'COMPARISON',
        fullyQualifiedName: 'TOKENS/OPERATORS/COMPARISON',
    }),
    new Token('resa', 11, 15, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(';', 12, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('yeet', 12, 7, {name: 'KEYWORD', fullyQualifiedName: 'TOKENS/KEYWORD'}),
    new Token('{', 12, 12, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('resa', 12, 13, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(',', 12, 17, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('resb', 12, 19, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token(',', 12, 23, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('resc', 12, 25, {name: 'IDENTIFIER', fullyQualifiedName: 'TOKENS/IDENTIFIER'}),
    new Token('}', 12, 29, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token(';', 13, 1, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
    new Token('}', 13, 3, {name: 'DELIMITER', fullyQualifiedName: 'TOKENS/DELIMITER'}),
];

export default tokens.reduce((str: string, token: Token) => str + token.toString() + '\n', '');
